package Model;
// Generated May 29, 2023 8:53:59 AM by Hibernate Tools 4.3.1



/**
 * Area generated by hbm2java
 */
public class Area  implements java.io.Serializable {


     private int idArea;
     private String nome;

    public Area() {
    }

	
    public Area(int idArea) {
        this.idArea = idArea;
    }
    public Area(int idArea, String nome) {
       this.idArea = idArea;
       this.nome = nome;
    }
   
    public int getIdArea() {
        return this.idArea;
    }
    
    public void setIdArea(int idArea) {
        this.idArea = idArea;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }




}


