package Model;
// Generated May 29, 2023 8:53:59 AM by Hibernate Tools 4.3.1



/**
 * Autor generated by hbm2java
 */
public class Autor  implements java.io.Serializable {


     private int idAutor;
     private String nome;
     private String apelido;

    public Autor() {
    }

	
    public Autor(int idAutor) {
        this.idAutor = idAutor;
    }
    public Autor(int idAutor, String nome, String apelido) {
       this.idAutor = idAutor;
       this.nome = nome;
       this.apelido = apelido;
    }
   
    public int getIdAutor() {
        return this.idAutor;
    }
    
    public void setIdAutor(int idAutor) {
        this.idAutor = idAutor;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getApelido() {
        return this.apelido;
    }
    
    public void setApelido(String apelido) {
        this.apelido = apelido;
    }




}


