package Model;
// Generated May 29, 2023 8:53:59 AM by Hibernate Tools 4.3.1



/**
 * Curso generated by hbm2java
 */
public class Curso  implements java.io.Serializable {


     private int idCurso;
     private String nome;
     private String abreviatura;

    public Curso() {
    }

	
    public Curso(int idCurso) {
        this.idCurso = idCurso;
    }
    public Curso(int idCurso, String nome, String abreviatura) {
       this.idCurso = idCurso;
       this.nome = nome;
       this.abreviatura = abreviatura;
    }
   
    public int getIdCurso() {
        return this.idCurso;
    }
    
    public void setIdCurso(int idCurso) {
        this.idCurso = idCurso;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getAbreviatura() {
        return this.abreviatura;
    }
    
    public void setAbreviatura(String abreviatura) {
        this.abreviatura = abreviatura;
    }




}


