package Model;
// Generated May 29, 2023 8:53:59 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Monografia generated by hbm2java
 */
public class Monografia  implements java.io.Serializable {


     private int idMonografia;
     private String titulo;
     private String autorId;
     private Date dataCadastro;

    public Monografia() {
    }

	
    public Monografia(int idMonografia) {
        this.idMonografia = idMonografia;
    }
    public Monografia(int idMonografia, String titulo, String autorId, Date dataCadastro) {
       this.idMonografia = idMonografia;
       this.titulo = titulo;
       this.autorId = autorId;
       this.dataCadastro = dataCadastro;
    }
   
    public int getIdMonografia() {
        return this.idMonografia;
    }
    
    public void setIdMonografia(int idMonografia) {
        this.idMonografia = idMonografia;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getAutorId() {
        return this.autorId;
    }
    
    public void setAutorId(String autorId) {
        this.autorId = autorId;
    }
    public Date getDataCadastro() {
        return this.dataCadastro;
    }
    
    public void setDataCadastro(Date dataCadastro) {
        this.dataCadastro = dataCadastro;
    }




}


