package Modelo.entidade;
// Generated 09/06/2023 00:04:05 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Areaconhecimento generated by hbm2java
 */
public class Areaconhecimento  implements java.io.Serializable {


     private Integer id;
     private String nome;
     private Set monografias = new HashSet(0);

    public Areaconhecimento() {
    }

	
    public Areaconhecimento(String nome) {
        this.nome = nome;
    }
    public Areaconhecimento(String nome, Set monografias) {
       this.nome = nome;
       this.monografias = monografias;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set getMonografias() {
        return this.monografias;
    }
    
    public void setMonografias(Set monografias) {
        this.monografias = monografias;
    }




}


