package modelo.entidade;
// Generated Jun 9, 2023 2:32:15 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Curso generated by hbm2java
 */
@Entity
@Table(name="curso"
    ,catalog="gestao_rpmonografia"
)
public class Curso  implements java.io.Serializable {


     private Integer id;
     private String nome;
     private Set<Monografia> monografias = new HashSet<Monografia>(0);

    public Curso() {
    }

	
    public Curso(String nome) {
        this.nome = nome;
    }
    public Curso(String nome, Set<Monografia> monografias) {
       this.nome = nome;
       this.monografias = monografias;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="nome", nullable=false, length=100)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="curso")
    public Set<Monografia> getMonografias() {
        return this.monografias;
    }
    
    public void setMonografias(Set<Monografia> monografias) {
        this.monografias = monografias;
    }




}


