package modelo.entidade;
// Generated Jun 9, 2023 2:32:15 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Monografia generated by hbm2java
 */
@Entity
@Table(name="monografia"
    ,catalog="gestao_rpmonografia"
)
public class Monografia  implements java.io.Serializable {


     private Integer id;
     private Areaconhecimento areaconhecimento;
     private Curso curso;
     private String titulo;
     private String assunto;
     private String autor;
     private Date dataPublicacao;
     private byte[] monografia;

    public Monografia() {
    }

	
    public Monografia(String titulo, String assunto, String autor) {
        this.titulo = titulo;
        this.assunto = assunto;
        this.autor = autor;
    }
    public Monografia(Areaconhecimento areaconhecimento, Curso curso, String titulo, String assunto, String autor, Date dataPublicacao, byte[] monografia) {
       this.areaconhecimento = areaconhecimento;
       this.curso = curso;
       this.titulo = titulo;
       this.assunto = assunto;
       this.autor = autor;
       this.dataPublicacao = dataPublicacao;
       this.monografia = monografia;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_area_conhecimento")
    public Areaconhecimento getAreaconhecimento() {
        return this.areaconhecimento;
    }
    
    public void setAreaconhecimento(Areaconhecimento areaconhecimento) {
        this.areaconhecimento = areaconhecimento;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_curso")
    public Curso getCurso() {
        return this.curso;
    }
    
    public void setCurso(Curso curso) {
        this.curso = curso;
    }

    
    @Column(name="titulo", nullable=false, length=100)
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    
    @Column(name="assunto", nullable=false, length=150)
    public String getAssunto() {
        return this.assunto;
    }
    
    public void setAssunto(String assunto) {
        this.assunto = assunto;
    }

    
    @Column(name="autor", nullable=false, length=100)
    public String getAutor() {
        return this.autor;
    }
    
    public void setAutor(String autor) {
        this.autor = autor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_publicacao", length=10)
    public Date getDataPublicacao() {
        return this.dataPublicacao;
    }
    
    public void setDataPublicacao(Date dataPublicacao) {
        this.dataPublicacao = dataPublicacao;
    }

    
    @Column(name="monografia")
    public byte[] getMonografia() {
        return this.monografia;
    }
    
    public void setMonografia(byte[] monografia) {
        this.monografia = monografia;
    }




}


